### PR TITLE
fix mck_io_num

### PR DESCRIPTION
**Pull request by apiel**
`mck_io_num` does not exist in `i2s_pin_config_t`

### CODE REVIEW

**Comment by pschatzmann** [comment]
How about using an actual ESP32 version. Why are you still using this old release ?

**Comment by apiel** [comment]
I don't know, I just git clone and run the example. When removing this line it worked...
How should I do to use the new release?

**Comment by pschatzmann** [comment]
Go to the Arduino Board Manager and install a recent ESP32 Release. The latest version is 2.0.6!

**Comment by pschatzmann** [comment]
If you want to keep your PR, please correct it to
#if ESP_IDF_VERSION > ESP_IDF_VERSION_VAL(4, 4, 0)                 
      KIT_LOGI("- mck_io_num: %d", pin_config.mck_io_num);
#endif

**Comment by apiel** [comment]
done

**Pull request merged**
